version: '3'

services:
  activemq-artemis:
    image: apache/activemq-artemis:latest
    ports:
      - "61616:61616"   # broker port
      - "8161:8161"     # web cosole port
      - "5672:5672"     # AMQP port
    environment:
      - ARTEMIS_USER=artemis-user
      - ARTEMIS_PASSWORD=artemis-password
    volumes:
      - ./data:/var/lib/activemq-artemis
